# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('paginaWeb', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('poblacion', models.CharField(max_length=250)),
                ('codigoPostal', models.IntegerField()),
                ('pais', models.CharField(max_length=250)),
            ],
        ),
    ]
