# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='direction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contacts.Direccion'),
            preserve_default=False,
        ),
    ]
