# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacto_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='direction',
        ),
    ]
