# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contacto_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='contacto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contacts.Contacto'),
            preserve_default=False,
        ),
    ]
