# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_direccion_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='country',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='localty',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='postal_code',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='route',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
