# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170619_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='country',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='localty',
            new_name='codigoPostal',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='postal_code',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='route',
            new_name='provincia',
        ),
    ]
