# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170619_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='contacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='codigoPostal',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='paginaWeb',
            new_name='pagina_web',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
